<?php

namespace DoctrineProxies\__CG__\Battleship\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cell extends \Battleship\Domain\Cell implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'board' => [parent::class, 'board', null],
        "\0".parent::class."\0".'coordinate' => [parent::class, 'coordinate', null],
        "\0".parent::class."\0".'guessed' => [parent::class, 'guessed', null],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null],
        "\0".parent::class."\0".'ship' => [parent::class, 'ship', null],
        'board' => [parent::class, 'board', null],
        'coordinate' => [parent::class, 'coordinate', null],
        'guessed' => [parent::class, 'guessed', null],
        'id' => [parent::class, 'id', parent::class],
        'messages' => [parent::class, 'messages', null],
        'ship' => [parent::class, 'ship', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
