<?php

namespace DoctrineProxies\__CG__\Battleship\Domain;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Board extends \Battleship\Domain\Board implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cells' => [parent::class, 'cells', null],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null],
        "\0".parent::class."\0".'ships' => [parent::class, 'ships', null],
        'cells' => [parent::class, 'cells', null],
        'id' => [parent::class, 'id', parent::class],
        'messages' => [parent::class, 'messages', null],
        'ships' => [parent::class, 'ships', null],
        'size' => [parent::class, 'size', parent::class],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
